// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumePasswordReset = `-- name: ConsumePasswordReset :exec
update password_resets set used_at = now() where token_hash = $1
`

func (q *Queries) ConsumePasswordReset(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, consumePasswordReset, tokenHash)
	return err
}

const createEvent = `-- name: CreateEvent :exec
insert into events (user_id, card_id, type, data)
values ($1, $2, $3, $4)
`

type CreateEventParams struct {
	UserID pgtype.UUID `json:"user_id"`
	CardID pgtype.UUID `json:"card_id"`
	Type   string      `json:"type"`
	Data   []byte      `json:"data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.UserID,
		arg.CardID,
		arg.Type,
		arg.Data,
	)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :exec
insert into password_resets (token_hash, user_id, expires_at)
values ($1, $2, $3)
`

type CreatePasswordResetParams struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error {
	_, err := q.db.Exec(ctx, createPasswordReset, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, user_id, token_hash, expires_at, revoked_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordReset = `-- name: GetPasswordReset :one
select token_hash, user_id, expires_at, used_at, created_at from password_resets
where token_hash = $1 and used_at is null and expires_at > now()
`

func (q *Queries) GetPasswordReset(ctx context.Context, tokenHash []byte) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordReset, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
select id, user_id, token_hash, expires_at, revoked_at, created_at from refresh_tokens
where token_hash = $1 and revoked_at is null and expires_at > now()
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
select e.id, e.user_id, e.card_id, e.type, e.data, e.created_at, u.username
from events e
left join users u on u.id = e.user_id
where ($1::text = '' or e.type = $1)
order by e.created_at desc
limit $2 offset $3
`

type ListEventsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListEventsRow struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CardID    pgtype.UUID        `json:"card_id"`
	Type      string             `json:"type"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  *string            `json:"username"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CardID,
			&i.Type,
			&i.Data,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
update refresh_tokens set revoked_at = now()
where user_id = $1 and revoked_at is null
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
update refresh_tokens set revoked_at = now() where token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
