// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: cards.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveCard = `-- name: ArchiveCard :exec
update cards set archived_at = now(), archive_reason = $3
where id = $1 and user_id = $2
`

type ArchiveCardParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"user_id"`
	ArchiveReason *string   `json:"archive_reason"`
}

func (q *Queries) ArchiveCard(ctx context.Context, arg ArchiveCardParams) error {
	_, err := q.db.Exec(ctx, archiveCard, arg.ID, arg.UserID, arg.ArchiveReason)
	return err
}

const createCard = `-- name: CreateCard :one
insert into cards (user_id, course_id, title, stage, position)
values ($1, $2, $3, 'planning', $4)
returning id, user_id, course_id, strategy_id, title, description, stage, position, difficulty, priority, pre_test, post_test, prior_knowledge, notes, rating, archived_at, archive_reason, created_at, updated_at
`

type CreateCardParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CourseID uuid.UUID `json:"course_id"`
	Title    string    `json:"title"`
	Position float64   `json:"position"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.UserID,
		arg.CourseID,
		arg.Title,
		arg.Position,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.StrategyID,
		&i.Title,
		&i.Description,
		&i.Stage,
		&i.Position,
		&i.Difficulty,
		&i.Priority,
		&i.PreTest,
		&i.PostTest,
		&i.PriorKnowledge,
		&i.Notes,
		&i.Rating,
		&i.ArchivedAt,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCardLink = `-- name: CreateCardLink :one

insert into card_links (card_id, url, label)
values ($1, $2, $3)
returning id, card_id, url, label
`

type CreateCardLinkParams struct {
	CardID uuid.UUID `json:"card_id"`
	Url    string    `json:"url"`
	Label  string    `json:"label"`
}

// Links
func (q *Queries) CreateCardLink(ctx context.Context, arg CreateCardLinkParams) (CardLink, error) {
	row := q.db.QueryRow(ctx, createCardLink, arg.CardID, arg.Url, arg.Label)
	var i CardLink
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Url,
		&i.Label,
	)
	return i, err
}

const createChecklistItem = `-- name: CreateChecklistItem :one

insert into checklist_items (card_id, text, position)
values ($1, $2, $3)
returning id, card_id, text, done, position
`

type CreateChecklistItemParams struct {
	CardID   uuid.UUID `json:"card_id"`
	Text     string    `json:"text"`
	Position float64   `json:"position"`
}

// Checklist items
func (q *Queries) CreateChecklistItem(ctx context.Context, arg CreateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, createChecklistItem, arg.CardID, arg.Text, arg.Position)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Text,
		&i.Done,
		&i.Position,
	)
	return i, err
}

const deleteCard = `-- name: DeleteCard :exec
delete from cards where id = $1 and user_id = $2
`

type DeleteCardParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCard(ctx context.Context, arg DeleteCardParams) error {
	_, err := q.db.Exec(ctx, deleteCard, arg.ID, arg.UserID)
	return err
}

const deleteCardLink = `-- name: DeleteCardLink :exec
delete from card_links where id = $1
`

func (q *Queries) DeleteCardLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCardLink, id)
	return err
}

const deleteChecklistItem = `-- name: DeleteChecklistItem :exec
delete from checklist_items where id = $1
`

func (q *Queries) DeleteChecklistItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChecklistItem, id)
	return err
}

const getActiveStudySession = `-- name: GetActiveStudySession :one
select id, user_id, card_id, started_at, ended_at from study_sessions where user_id = $1 and ended_at is null
`

func (q *Queries) GetActiveStudySession(ctx context.Context, userID uuid.UUID) (StudySession, error) {
	row := q.db.QueryRow(ctx, getActiveStudySession, userID)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const getCard = `-- name: GetCard :one
select id, user_id, course_id, strategy_id, title, description, stage, position, difficulty, priority, pre_test, post_test, prior_knowledge, notes, rating, archived_at, archive_reason, created_at, updated_at from cards where id = $1 and user_id = $2
`

type GetCardParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCard(ctx context.Context, arg GetCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, getCard, arg.ID, arg.UserID)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.StrategyID,
		&i.Title,
		&i.Description,
		&i.Stage,
		&i.Position,
		&i.Difficulty,
		&i.Priority,
		&i.PreTest,
		&i.PostTest,
		&i.PriorKnowledge,
		&i.Notes,
		&i.Rating,
		&i.ArchivedAt,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardAnyUser = `-- name: GetCardAnyUser :one
select id, user_id, course_id, strategy_id, title, description, stage, position, difficulty, priority, pre_test, post_test, prior_knowledge, notes, rating, archived_at, archive_reason, created_at, updated_at from cards where id = $1
`

func (q *Queries) GetCardAnyUser(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardAnyUser, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.StrategyID,
		&i.Title,
		&i.Description,
		&i.Stage,
		&i.Position,
		&i.Difficulty,
		&i.Priority,
		&i.PreTest,
		&i.PostTest,
		&i.PriorKnowledge,
		&i.Notes,
		&i.Rating,
		&i.ArchivedAt,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCardWithCourse = `-- name: GetCardWithCourse :one
select c.id, c.user_id, c.course_id, c.strategy_id, c.title, c.description, c.stage, c.position, c.difficulty, c.priority, c.pre_test, c.post_test, c.prior_knowledge, c.notes, c.rating, c.archived_at, c.archive_reason, c.created_at, c.updated_at, co.code as course_code, co.name as course_name, ls.name as strategy_name
from cards c
join courses co on co.id = c.course_id
left join learning_strategies ls on ls.id = c.strategy_id
where c.id = $1 and c.user_id = $2
`

type GetCardWithCourseParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetCardWithCourseRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	CourseID       uuid.UUID          `json:"course_id"`
	StrategyID     pgtype.UUID        `json:"strategy_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Stage          SrlStage           `json:"stage"`
	Position       float64            `json:"position"`
	Difficulty     Difficulty         `json:"difficulty"`
	Priority       Priority           `json:"priority"`
	PreTest        pgtype.Numeric     `json:"pre_test"`
	PostTest       pgtype.Numeric     `json:"post_test"`
	PriorKnowledge string             `json:"prior_knowledge"`
	Notes          string             `json:"notes"`
	Rating         *int16             `json:"rating"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	ArchiveReason  *string            `json:"archive_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CourseCode     string             `json:"course_code"`
	CourseName     string             `json:"course_name"`
	StrategyName   *string            `json:"strategy_name"`
}

func (q *Queries) GetCardWithCourse(ctx context.Context, arg GetCardWithCourseParams) (GetCardWithCourseRow, error) {
	row := q.db.QueryRow(ctx, getCardWithCourse, arg.ID, arg.UserID)
	var i GetCardWithCourseRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.StrategyID,
		&i.Title,
		&i.Description,
		&i.Stage,
		&i.Position,
		&i.Difficulty,
		&i.Priority,
		&i.PreTest,
		&i.PostTest,
		&i.PriorKnowledge,
		&i.Notes,
		&i.Rating,
		&i.ArchivedAt,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CourseCode,
		&i.CourseName,
		&i.StrategyName,
	)
	return i, err
}

const listActiveCards = `-- name: ListActiveCards :many
select c.id, c.user_id, c.course_id, c.strategy_id, c.title, c.description, c.stage, c.position, c.difficulty, c.priority, c.pre_test, c.post_test, c.prior_knowledge, c.notes, c.rating, c.archived_at, c.archive_reason, c.created_at, c.updated_at, co.code as course_code, co.name as course_name, ls.name as strategy_name
from cards c
join courses co on co.id = c.course_id
left join learning_strategies ls on ls.id = c.strategy_id
where c.user_id = $1 and c.archived_at is null
order by c.stage, c.position
`

type ListActiveCardsRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	CourseID       uuid.UUID          `json:"course_id"`
	StrategyID     pgtype.UUID        `json:"strategy_id"`
	Title          string             `json:"title"`
	Description    string             `json:"description"`
	Stage          SrlStage           `json:"stage"`
	Position       float64            `json:"position"`
	Difficulty     Difficulty         `json:"difficulty"`
	Priority       Priority           `json:"priority"`
	PreTest        pgtype.Numeric     `json:"pre_test"`
	PostTest       pgtype.Numeric     `json:"post_test"`
	PriorKnowledge string             `json:"prior_knowledge"`
	Notes          string             `json:"notes"`
	Rating         *int16             `json:"rating"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
	ArchiveReason  *string            `json:"archive_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CourseCode     string             `json:"course_code"`
	CourseName     string             `json:"course_name"`
	StrategyName   *string            `json:"strategy_name"`
}

func (q *Queries) ListActiveCards(ctx context.Context, userID uuid.UUID) ([]ListActiveCardsRow, error) {
	rows, err := q.db.Query(ctx, listActiveCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCardsRow
	for rows.Next() {
		var i ListActiveCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.StrategyID,
			&i.Title,
			&i.Description,
			&i.Stage,
			&i.Position,
			&i.Difficulty,
			&i.Priority,
			&i.PreTest,
			&i.PostTest,
			&i.PriorKnowledge,
			&i.Notes,
			&i.Rating,
			&i.ArchivedAt,
			&i.ArchiveReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CourseCode,
			&i.CourseName,
			&i.StrategyName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArchivedCards = `-- name: ListArchivedCards :many
select id, user_id, course_id, strategy_id, title, description, stage, position, difficulty, priority, pre_test, post_test, prior_knowledge, notes, rating, archived_at, archive_reason, created_at, updated_at from cards
where user_id = $1 and archived_at is not null
order by archived_at desc
`

func (q *Queries) ListArchivedCards(ctx context.Context, userID uuid.UUID) ([]Card, error) {
	rows, err := q.db.Query(ctx, listArchivedCards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CourseID,
			&i.StrategyID,
			&i.Title,
			&i.Description,
			&i.Stage,
			&i.Position,
			&i.Difficulty,
			&i.Priority,
			&i.PreTest,
			&i.PostTest,
			&i.PriorKnowledge,
			&i.Notes,
			&i.Rating,
			&i.ArchivedAt,
			&i.ArchiveReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecklistItemsByCardIDs = `-- name: ListChecklistItemsByCardIDs :many
select id, card_id, text, done, position from checklist_items where card_id = any($1::uuid[]) order by position
`

func (q *Queries) ListChecklistItemsByCardIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ChecklistItem, error) {
	rows, err := q.db.Query(ctx, listChecklistItemsByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChecklistItem
	for rows.Next() {
		var i ChecklistItem
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Text,
			&i.Done,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksByCardIDs = `-- name: ListLinksByCardIDs :many
select id, card_id, url, label from card_links where card_id = any($1::uuid[]) order by id
`

func (q *Queries) ListLinksByCardIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]CardLink, error) {
	rows, err := q.db.Query(ctx, listLinksByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CardLink
	for rows.Next() {
		var i CardLink
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.Url,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveCard = `-- name: MoveCard :one
update cards
set stage = $3, position = $4, updated_at = now()
where id = $1 and user_id = $2
returning id, user_id, course_id, strategy_id, title, description, stage, position, difficulty, priority, pre_test, post_test, prior_knowledge, notes, rating, archived_at, archive_reason, created_at, updated_at
`

type MoveCardParams struct {
	ID       uuid.UUID `json:"id"`
	UserID   uuid.UUID `json:"user_id"`
	Stage    SrlStage  `json:"stage"`
	Position float64   `json:"position"`
}

func (q *Queries) MoveCard(ctx context.Context, arg MoveCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, moveCard,
		arg.ID,
		arg.UserID,
		arg.Stage,
		arg.Position,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.StrategyID,
		&i.Title,
		&i.Description,
		&i.Stage,
		&i.Position,
		&i.Difficulty,
		&i.Priority,
		&i.PreTest,
		&i.PostTest,
		&i.PriorKnowledge,
		&i.Notes,
		&i.Rating,
		&i.ArchivedAt,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextChecklistPosition = `-- name: NextChecklistPosition :one
select (coalesce(max(position), 0) + 1024)::float8 as next_position from checklist_items where card_id = $1
`

func (q *Queries) NextChecklistPosition(ctx context.Context, cardID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, nextChecklistPosition, cardID)
	var next_position float64
	err := row.Scan(&next_position)
	return next_position, err
}

const nextPositionInStage = `-- name: NextPositionInStage :one
select (coalesce(max(position), 0) + 1024)::float8 as next_position
from cards
where user_id = $1 and stage = $2 and archived_at is null
`

type NextPositionInStageParams struct {
	UserID uuid.UUID `json:"user_id"`
	Stage  SrlStage  `json:"stage"`
}

func (q *Queries) NextPositionInStage(ctx context.Context, arg NextPositionInStageParams) (float64, error) {
	row := q.db.QueryRow(ctx, nextPositionInStage, arg.UserID, arg.Stage)
	var next_position float64
	err := row.Scan(&next_position)
	return next_position, err
}

const restoreCard = `-- name: RestoreCard :exec
update cards set archived_at = null, archive_reason = null
where id = $1 and user_id = $2
`

type RestoreCardParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RestoreCard(ctx context.Context, arg RestoreCardParams) error {
	_, err := q.db.Exec(ctx, restoreCard, arg.ID, arg.UserID)
	return err
}

const startStudySession = `-- name: StartStudySession :one

insert into study_sessions (user_id, card_id)
values ($1, $2)
returning id, user_id, card_id, started_at, ended_at
`

type StartStudySessionParams struct {
	UserID uuid.UUID `json:"user_id"`
	CardID uuid.UUID `json:"card_id"`
}

// Study sessions
func (q *Queries) StartStudySession(ctx context.Context, arg StartStudySessionParams) (StudySession, error) {
	row := q.db.QueryRow(ctx, startStudySession, arg.UserID, arg.CardID)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CardID,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const stopStudySession = `-- name: StopStudySession :exec
update study_sessions set ended_at = now()
where user_id = $1 and ended_at is null
`

func (q *Queries) StopStudySession(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, stopStudySession, userID)
	return err
}

const totalStudyMinutesByCardIDs = `-- name: TotalStudyMinutesByCardIDs :many
select card_id, coalesce(sum(extract(epoch from (coalesce(ended_at, now()) - started_at)) / 60), 0)::float8 as minutes
from study_sessions
where card_id = any($1::uuid[])
group by card_id
`

type TotalStudyMinutesByCardIDsRow struct {
	CardID  uuid.UUID `json:"card_id"`
	Minutes float64   `json:"minutes"`
}

func (q *Queries) TotalStudyMinutesByCardIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]TotalStudyMinutesByCardIDsRow, error) {
	rows, err := q.db.Query(ctx, totalStudyMinutesByCardIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TotalStudyMinutesByCardIDsRow
	for rows.Next() {
		var i TotalStudyMinutesByCardIDsRow
		if err := rows.Scan(&i.CardID, &i.Minutes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardDetail = `-- name: UpdateCardDetail :one
update cards set
  description = $3,
  strategy_id = $4,
  difficulty = $5,
  priority = $6,
  pre_test = $7,
  post_test = $8,
  prior_knowledge = $9,
  notes = $10,
  rating = $11,
  updated_at = now()
where id = $1 and user_id = $2
returning id, user_id, course_id, strategy_id, title, description, stage, position, difficulty, priority, pre_test, post_test, prior_knowledge, notes, rating, archived_at, archive_reason, created_at, updated_at
`

type UpdateCardDetailParams struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	Description    string         `json:"description"`
	StrategyID     pgtype.UUID    `json:"strategy_id"`
	Difficulty     Difficulty     `json:"difficulty"`
	Priority       Priority       `json:"priority"`
	PreTest        pgtype.Numeric `json:"pre_test"`
	PostTest       pgtype.Numeric `json:"post_test"`
	PriorKnowledge string         `json:"prior_knowledge"`
	Notes          string         `json:"notes"`
	Rating         *int16         `json:"rating"`
}

func (q *Queries) UpdateCardDetail(ctx context.Context, arg UpdateCardDetailParams) (Card, error) {
	row := q.db.QueryRow(ctx, updateCardDetail,
		arg.ID,
		arg.UserID,
		arg.Description,
		arg.StrategyID,
		arg.Difficulty,
		arg.Priority,
		arg.PreTest,
		arg.PostTest,
		arg.PriorKnowledge,
		arg.Notes,
		arg.Rating,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.StrategyID,
		&i.Title,
		&i.Description,
		&i.Stage,
		&i.Position,
		&i.Difficulty,
		&i.Priority,
		&i.PreTest,
		&i.PostTest,
		&i.PriorKnowledge,
		&i.Notes,
		&i.Rating,
		&i.ArchivedAt,
		&i.ArchiveReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateChecklistItem = `-- name: UpdateChecklistItem :one
update checklist_items set text = $2, done = $3 where id = $1
returning id, card_id, text, done, position
`

type UpdateChecklistItemParams struct {
	ID   uuid.UUID `json:"id"`
	Text string    `json:"text"`
	Done bool      `json:"done"`
}

func (q *Queries) UpdateChecklistItem(ctx context.Context, arg UpdateChecklistItemParams) (ChecklistItem, error) {
	row := q.db.QueryRow(ctx, updateChecklistItem, arg.ID, arg.Text, arg.Done)
	var i ChecklistItem
	err := row.Scan(
		&i.ID,
		&i.CardID,
		&i.Text,
		&i.Done,
		&i.Position,
	)
	return i, err
}
