// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: courses.sql

package sqlcgen

import (
	"context"
)

const listCourses = `-- name: ListCourses :many
select id, program_id, code, name, created_at from courses order by code
`

func (q *Queries) ListCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.ProgramID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStrategies = `-- name: ListStrategies :many
select id, name, description, created_at from learning_strategies order by name
`

func (q *Queries) ListStrategies(ctx context.Context) ([]LearningStrategy, error) {
	rows, err := q.db.Query(ctx, listStrategies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningStrategy
	for rows.Next() {
		var i LearningStrategy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
