// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: programs.sql

package sqlcgen

import (
	"context"
)

const getProgramByCode = `-- name: GetProgramByCode :one
select id, code, name, created_at from programs where code = $1
`

func (q *Queries) GetProgramByCode(ctx context.Context, code string) (Program, error) {
	row := q.db.QueryRow(ctx, getProgramByCode, code)
	var i Program
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listPrograms = `-- name: ListPrograms :many
select id, code, name, created_at from programs order by name
`

func (q *Queries) ListPrograms(ctx context.Context) ([]Program, error) {
	rows, err := q.db.Query(ctx, listPrograms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Program
	for rows.Next() {
		var i Program
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
