// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumePasswordReset(ctx context.Context, tokenHash []byte) error
	CountUsers(ctx context.Context) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetPasswordReset(ctx context.Context, tokenHash []byte) (PasswordReset, error)
	GetProgramByCode(ctx context.Context, code string) (Program, error)
	GetRefreshToken(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListEvents(ctx context.Context, arg ListEventsParams) ([]ListEventsRow, error)
	ListPrograms(ctx context.Context) ([]Program, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkUserOnboarded(ctx context.Context, id uuid.UUID) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash []byte) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
