// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, username, password_hash, first_name, last_name, role, program_id)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, email, username, password_hash, first_name, last_name, role, program_id, onboarded_at, created_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	FirstName    string      `json:"first_name"`
	LastName     string      `json:"last_name"`
	Role         UserRole    `json:"role"`
	ProgramID    pgtype.UUID `json:"program_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.Role,
		arg.ProgramID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProgramID,
		&i.OnboardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
select id, email, username, password_hash, first_name, last_name, role, program_id, onboarded_at, created_at from users where email = $1 or username = $1
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProgramID,
		&i.OnboardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, username, password_hash, first_name, last_name, role, program_id, onboarded_at, created_at from users where id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProgramID,
		&i.OnboardedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select id, email, username, password_hash, first_name, last_name, role, program_id, onboarded_at, created_at from users
where ($1::text = '' or email ilike '%' || $1 || '%' or username ilike '%' || $1 || '%'
       or first_name ilike '%' || $1 || '%' or last_name ilike '%' || $1 || '%')
order by created_at desc
limit $2 offset $3
`

type ListUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Role,
			&i.ProgramID,
			&i.OnboardedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markUserOnboarded = `-- name: MarkUserOnboarded :exec
update users set onboarded_at = now() where id = $1
`

func (q *Queries) MarkUserOnboarded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markUserOnboarded, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
update users set password_hash = $2 where id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
update users
set first_name = $2, last_name = $3, email = $4, username = $5
where id = $1
returning id, email, username, password_hash, first_name, last_name, role, program_id, onboarded_at, created_at
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	Email     string    `json:"email"`
	Username  string    `json:"username"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Username,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Role,
		&i.ProgramID,
		&i.OnboardedAt,
		&i.CreatedAt,
	)
	return i, err
}
